.tag-hog: &tag-hog
  tags:
     - hog

.tag-sr: &tag-sr
  tags:
     - docker

.only-default: &only-default
  only:
    refs:
      - merge_requests
      - main # or name of the default official branch
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^test\/.*$/i
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:.*$/ && $CI_COMMIT_MESSAGE !~ /^RESOLVE_WIP:/


#registers-job:
#  <<: *only-default
#  <<: *tag-hog
#  stage: user_pre
#  script: "make reg"

daq-sim-job:
  variables:
    GIT_STRATEGY: clone
  <<: *only-default
  <<: *tag-hog
  stage: user_pre
  script: "cd trigger/src/trg && python test_trigger.py"

# daq-sim-job:
#   variables:
#     GIT_STRATEGY: clone
#   <<: *only-default
#   <<: *tag-hog
#   stage: user_pre
#   script: "make -C drs/"
