#!/usr/bin/env python3
import sys
import generate_registers as reg

CONFIG = {
    'TOP_NODE_NAME'                 : 'DRS',
    'ADDRESS_TABLE_TOP'             : '../rb_registers.xml',
    'CONSTANTS_FILE'                : '../drs/src/registers.vhd',
    'DOC_FILE'                      : './rb_address_table.tex',
    'JSON_FILE'                     : '../util/rb_addresses.json',
    'ORG_FILE'                      : './rb_address_table.org',
    'PACKAGE_FILE'                  : '../drs/src/ipbus_pkg.vhd',
    'VHDL_REG_GENERATED_DISCLAIMER' : '(this section is generated by generate_registers.py -- do not edit)'
}


if __name__ == '__main__':
    reg.main(CONFIG)
