#!/usr/bin/env python3
import sys
import generate_registers as reg

CONFIG = {
    'TOP_NODE_NAME'                 : 'MT',
    'ADDRESS_TABLE_TOP'             : '../mt_registers.xml',
    'CONSTANTS_FILE'                : '../trigger/src/infra/registers.vhd',
    'DOC_FILE'                      : './mt_address_table.tex',
    'JSON_FILE'                     : '../util/mt_addresses.json',
    'ORG_FILE'                      : './mt_address_table.org',
    'PACKAGE_FILE'                  : '../trigger/src/infra/ipbus_pkg.vhd',
    'VHDL_REG_GENERATED_DISCLAIMER' : '(this section is generated by generate_registers.py -- do not edit)'
}

if __name__ == '__main__':
    reg.main(CONFIG)
