#!/usr/bin/env python2
import sys
import generate_registers as reg

CONFIG = {
    'TOP_NODE_NAME'                 : 'DRS',
    'ADDRESS_TABLE_TOP'             : '../registers.xml',
    'CONSTANTS_FILE'                : '../drs/src/registers.vhd',
    'DOC_FILE'                      : './address_table.tex',
    'ORG_FILE'                      : './address_table.org',
    'PACKAGE_FILE'                  : '../drs/src/ipbus_pkg.vhd',
    'VHDL_REG_GENERATED_DISCLAIMER' : '(this section is generated by generate_registers.py -- do not edit)'
}


if __name__ == '__main__':
    if sys.version_info[0] >= 3:
        raise Exception("Python 2 required.")
    reg.main (CONFIG)
