# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Ismael/Documents/GAPS/DMA/tcl/.Xil/Vivado-2284-DESKTOP-EO01TL4/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/verilog
    c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/ila_0/hdl/verilog
  } {
      D:/Xilinx_2018.2/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx_2018.2/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/verilog
    c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/ila_0/hdl/verilog
  } {
      C:/Users/Ismael/Documents/GAPS/DMA/hdl/DMA_Write_v1_0.v
      C:/Users/Ismael/Documents/GAPS/DMA/hdl/DMA_Write_v1_0_M00_AXI.v
      C:/Users/Ismael/Documents/GAPS/DMA/hdl/DMA_WRITE_v1_0_STATUS.v
      C:/Users/Ismael/Documents/GAPS/DMA/hdl/DMA_WRITE_v1_0_IRQ.v
      c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/ltlib_v1_0_vl_rfs.v
      c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/xsdbs_v1_0_vl_rfs.v
      c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/xsdbm_v3_0_vl_rfs.v
      c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/ila_v6_2_syn_rfs.v
      c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/synth/dma_ila.v
      c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/ila_0/synth/ila_0.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_6 c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_4 c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/dma_ila/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_1 c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/fifo_generator_1/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_2 c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/fifo_generator_1/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib c:/Users/Ismael/Documents/GAPS/DMA/ip_sources/fifo_generator_1/synth/fifo_generator_1.vhd
      rt::read_vhdl -lib xpm D:/Xilinx_2018.2/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/Ismael/Documents/GAPS/DMA/tcl/.Xil/Vivado-2284-DESKTOP-EO01TL4/realtime/DMA_Write_v1_0_synth.xdc
    rt::sdcChecksum
    set rt::top DMA_Write_v1_0
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/Ismael/Documents/GAPS/DMA/tcl/.Xil/Vivado-2284-DESKTOP-EO01TL4/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/Ismael/Documents/GAPS/DMA/tcl/.Xil/Vivado-2284-DESKTOP-EO01TL4/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
