set_property -dict [list \
                        CONFIG.C_PROBE_OUT0_WIDTH {1} \
                        CONFIG.C_PROBE_OUT1_WIDTH {75} \
                        CONFIG.C_PROBE_OUT2_WIDTH {50} \
                        CONFIG.C_PROBE_OUT3_WIDTH {1} \
                        CONFIG.C_PROBE_OUT4_WIDTH {5} \
                        CONFIG.C_PROBE_OUT5_WIDTH {4} \
                        CONFIG.C_PROBE_IN0_WIDTH {32} \
                        CONFIG.C_PROBE_IN1_WIDTH {10} \
                        CONFIG.C_PROBE_IN2_WIDTH {10} \
                        CONFIG.C_PROBE_IN3_WIDTH {10} \
                        CONFIG.C_PROBE_IN4_WIDTH {10} \
                        CONFIG.C_PROBE_IN5_WIDTH {10} \
                        CONFIG.C_PROBE_IN6_WIDTH {10} \
                        CONFIG.C_PROBE_IN7_WIDTH {10} \
                        CONFIG.C_PROBE_IN8_WIDTH {10} \
                        CONFIG.C_PROBE_IN9_WIDTH {10} \
                        CONFIG.C_PROBE_IN10_WIDTH {10} \
                        CONFIG.C_PROBE_IN11_WIDTH {10} \
                        CONFIG.C_PROBE_IN12_WIDTH {10} \
                        CONFIG.C_PROBE_IN13_WIDTH {10} \
                        CONFIG.C_PROBE_IN14_WIDTH {10} \
                        CONFIG.C_PROBE_IN15_WIDTH {10} \
                        CONFIG.C_PROBE_IN16_WIDTH {10} \
                        CONFIG.C_PROBE_IN17_WIDTH {10} \
                        CONFIG.C_PROBE_IN18_WIDTH {10} \
                        CONFIG.C_PROBE_IN19_WIDTH {10} \
                        CONFIG.C_PROBE_IN20_WIDTH {10} \
                        CONFIG.C_PROBE_IN21_WIDTH {10} \
                        CONFIG.C_PROBE_IN22_WIDTH {10} \
                        CONFIG.C_PROBE_IN23_WIDTH {10} \
                        CONFIG.C_PROBE_IN24_WIDTH {10} \
                        CONFIG.C_PROBE_IN25_WIDTH {10} \
                        CONFIG.C_PROBE_IN26_WIDTH {10} \
                        CONFIG.C_PROBE_IN27_WIDTH {10} \
                        CONFIG.C_PROBE_IN28_WIDTH {10} \
                        CONFIG.C_PROBE_IN29_WIDTH {10} \
                        CONFIG.C_PROBE_IN30_WIDTH {10} \
                        CONFIG.C_PROBE_IN31_WIDTH {10} \
                        CONFIG.C_PROBE_IN32_WIDTH {10} \
                        CONFIG.C_PROBE_IN33_WIDTH {10} \
                        CONFIG.C_PROBE_IN34_WIDTH {10} \
                        CONFIG.C_PROBE_IN35_WIDTH {10} \
                        CONFIG.C_PROBE_IN36_WIDTH {10} \
                        CONFIG.C_PROBE_IN37_WIDTH {10} \
                        CONFIG.C_PROBE_IN38_WIDTH {10} \
                        CONFIG.C_PROBE_IN39_WIDTH {10} \
                        CONFIG.C_PROBE_IN40_WIDTH {10} \
                        CONFIG.C_PROBE_IN41_WIDTH {10} \
                        CONFIG.C_PROBE_IN42_WIDTH {10} \
                        CONFIG.C_PROBE_IN43_WIDTH {10} \
                        CONFIG.C_PROBE_IN44_WIDTH {10} \
                        CONFIG.C_PROBE_IN45_WIDTH {10} \
                        CONFIG.C_PROBE_IN46_WIDTH {10} \
                        CONFIG.C_PROBE_IN47_WIDTH {10} \
                        CONFIG.C_PROBE_IN48_WIDTH {10} \
                        CONFIG.C_PROBE_IN49_WIDTH {10} \
                        CONFIG.C_PROBE_IN50_WIDTH {10} \
                        CONFIG.C_PROBE_IN51_WIDTH {10} \
                        CONFIG.C_PROBE_IN52_WIDTH {10} \
                        CONFIG.C_PROBE_IN53_WIDTH {10} \
                        CONFIG.C_PROBE_IN54_WIDTH {10} \
                        CONFIG.C_PROBE_IN55_WIDTH {10} \
                        CONFIG.C_PROBE_IN56_WIDTH {10} \
                        CONFIG.C_PROBE_IN57_WIDTH {10} \
                        CONFIG.C_PROBE_IN58_WIDTH {10} \
                        CONFIG.C_PROBE_IN59_WIDTH {10} \
                        CONFIG.C_PROBE_IN60_WIDTH {10} \
                        CONFIG.C_PROBE_IN61_WIDTH {10} \
                        CONFIG.C_PROBE_IN62_WIDTH {10} \
                        CONFIG.C_PROBE_IN63_WIDTH {10} \
                        CONFIG.C_PROBE_IN64_WIDTH {10} \
                        CONFIG.C_PROBE_IN65_WIDTH {10} \
                        CONFIG.C_PROBE_IN66_WIDTH {10} \
                        CONFIG.C_PROBE_IN67_WIDTH {10} \
                        CONFIG.C_PROBE_IN68_WIDTH {10} \
                        CONFIG.C_PROBE_IN69_WIDTH {10} \
                        CONFIG.C_PROBE_IN70_WIDTH {10} \
                        CONFIG.C_PROBE_IN71_WIDTH {10} \
                        CONFIG.C_PROBE_IN72_WIDTH {10} \
                        CONFIG.C_PROBE_IN73_WIDTH {10} \
                        CONFIG.C_PROBE_IN74_WIDTH {10} \
                        CONFIG.C_PROBE_IN75_WIDTH {10} \
                        CONFIG.C_PROBE_IN76_WIDTH {75} \
                        CONFIG.C_PROBE_IN77_WIDTH {4} \
                        CONFIG.C_NUM_PROBE_OUT {6} \
                        CONFIG.C_NUM_PROBE_IN {78}] \
    [get_ips vio_prbs]
