set_property PACKAGE_PIN  H18 [get_ports                clk_n]; # P1 B20
set_property PACKAGE_PIN  H17 [get_ports                clk_p]; # P1 A20
set_property PACKAGE_PIN AC12 [get_ports          clk_src_sel]; # P2 F30
set_property PACKAGE_PIN   U9 [get_ports            dsi_on[0]]; # P2 E26
set_property PACKAGE_PIN  AA8 [get_ports            dsi_on[1]]; # P2 A27
set_property PACKAGE_PIN  AC9 [get_ports            dsi_on[2]]; # P2 A29
set_property PACKAGE_PIN AC11 [get_ports            dsi_on[3]]; # P2 C30
set_property PACKAGE_PIN AF12 [get_ports            dsi_on[4]]; # P2 B33
set_property PACKAGE_PIN AB11 [get_ports            ext_in[0]]; # P2 B30
set_property PACKAGE_PIN  Y12 [get_ports            ext_in[1]]; # P2 E31
set_property PACKAGE_PIN AA12 [get_ports            ext_in[2]]; # P2 B31
set_property PACKAGE_PIN AA13 [get_ports            ext_in[3]]; # P2 A31
set_property PACKAGE_PIN  Y13 [get_ports            ext_io[0]]; # P2 D31
set_property PACKAGE_PIN AE13 [get_ports           ext_io[10]]; # P2 D33
set_property PACKAGE_PIN AE12 [get_ports           ext_io[11]]; # P2 A33
set_property PACKAGE_PIN  AE7 [get_ports           ext_io[12]]; # P2 B26
set_property PACKAGE_PIN  AF7 [get_ports           ext_io[13]]; # P2 C26
set_property PACKAGE_PIN AE10 [get_ports            ext_io[1]]; # P2 F32
set_property PACKAGE_PIN AD13 [get_ports            ext_io[2]]; # P2 C32
set_property PACKAGE_PIN AF13 [get_ports            ext_io[3]]; # P2 E33
set_property PACKAGE_PIN  AA7 [get_ports            ext_io[4]]; # P2 B27
set_property PACKAGE_PIN  AC8 [get_ports            ext_io[5]]; # P2 B28
set_property PACKAGE_PIN  AC7 [get_ports            ext_io[6]]; # P2 E27
set_property PACKAGE_PIN AB12 [get_ports            ext_io[7]]; # P2 E30
set_property PACKAGE_PIN AD10 [get_ports            ext_io[8]]; # P2 E32
set_property PACKAGE_PIN AC13 [get_ports            ext_io[9]]; # P2 B32
set_property PACKAGE_PIN  AB7 [get_ports           ext_out[0]]; # P2 D27
set_property PACKAGE_PIN  AA9 [get_ports           ext_out[1]]; # P2 E28
set_property PACKAGE_PIN  AD9 [get_ports           ext_out[2]]; # P2 B29
set_property PACKAGE_PIN AB10 [get_ports           ext_out[3]]; # P2 E29
set_property PACKAGE_PIN  A17 [get_ports          fb_clk_n[0]]; # P1 B14
set_property PACKAGE_PIN  B16 [get_ports          fb_clk_n[1]]; # P1 C13
set_property PACKAGE_PIN  F15 [get_ports          fb_clk_n[2]]; # P1 B16
set_property PACKAGE_PIN  G16 [get_ports          fb_clk_n[3]]; # P1 C15
set_property PACKAGE_PIN  E16 [get_ports          fb_clk_n[4]]; # P1 B18
set_property PACKAGE_PIN  B17 [get_ports          fb_clk_p[0]]; # P1 A14
set_property PACKAGE_PIN  C16 [get_ports          fb_clk_p[1]]; # P1 B13
set_property PACKAGE_PIN  G15 [get_ports          fb_clk_p[2]]; # P1 A16
set_property PACKAGE_PIN  H16 [get_ports          fb_clk_p[3]]; # P1 B15
set_property PACKAGE_PIN  E15 [get_ports          fb_clk_p[4]]; # P1 A18
set_property PACKAGE_PIN  B22 [get_ports               hk_clk]; # P2 A37
set_property PACKAGE_PIN  A22 [get_ports           hk_cs_n[0]]; # P2 D36
set_property PACKAGE_PIN  C23 [get_ports           hk_cs_n[1]]; # P2 E36
set_property PACKAGE_PIN  B24 [get_ports               hk_din]; # P2 C36
set_property PACKAGE_PIN  A25 [get_ports              hk_dout]; # P2 C37
set_property PACKAGE_PIN  U25 [get_ports       lt_data_i_n[0]]; # P2 B1
set_property PACKAGE_PIN   G9 [get_ports      lt_data_i_n[10]]; # P1 F31
set_property PACKAGE_PIN  H13 [get_ports      lt_data_i_n[11]]; # P1 E34
set_property PACKAGE_PIN AA20 [get_ports      lt_data_i_n[12]]; # P2 C22
set_property PACKAGE_PIN  V19 [get_ports      lt_data_i_n[13]]; # P2 B25
set_property PACKAGE_PIN  V17 [get_ports      lt_data_i_n[14]]; # P2 C24
set_property PACKAGE_PIN  W26 [get_ports      lt_data_i_n[15]]; # P2 C4
set_property PACKAGE_PIN  W24 [get_ports      lt_data_i_n[16]]; # P2 B5
set_property PACKAGE_PIN AC26 [get_ports      lt_data_i_n[17]]; # P2 C6
set_property PACKAGE_PIN AB24 [get_ports      lt_data_i_n[18]]; # P2 F6
set_property PACKAGE_PIN AC21 [get_ports      lt_data_i_n[19]]; # P2 E9
set_property PACKAGE_PIN  V22 [get_ports       lt_data_i_n[1]]; # P2 C2
set_property PACKAGE_PIN  Y21 [get_ports      lt_data_i_n[20]]; # P2 F8
set_property PACKAGE_PIN   A8 [get_ports      lt_data_i_n[21]]; # P1 B32
set_property PACKAGE_PIN   B9 [get_ports      lt_data_i_n[22]]; # P1 C33
set_property PACKAGE_PIN  C11 [get_ports      lt_data_i_n[23]]; # P1 B34
set_property PACKAGE_PIN  G14 [get_ports      lt_data_i_n[24]]; # P1 F33
set_property PACKAGE_PIN  J10 [get_ports      lt_data_i_n[25]]; # P1 E36
set_property PACKAGE_PIN  H11 [get_ports      lt_data_i_n[26]]; # P1 F35
set_property PACKAGE_PIN AA15 [get_ports      lt_data_i_n[27]]; # P2 E17
set_property PACKAGE_PIN AD18 [get_ports      lt_data_i_n[28]]; # P2 F18
set_property PACKAGE_PIN AB15 [get_ports      lt_data_i_n[29]]; # P2 E19
set_property PACKAGE_PIN  V26 [get_ports       lt_data_i_n[2]]; # P2 B3
set_property PACKAGE_PIN AA24 [get_ports      lt_data_i_n[30]]; # P2 B7
set_property PACKAGE_PIN AA22 [get_ports      lt_data_i_n[31]]; # P2 C8
set_property PACKAGE_PIN AD24 [get_ports      lt_data_i_n[32]]; # P2 B9
set_property PACKAGE_PIN AF23 [get_ports      lt_data_i_n[33]]; # P2 E11
set_property PACKAGE_PIN AE21 [get_ports      lt_data_i_n[34]]; # P2 F10
set_property PACKAGE_PIN AE25 [get_ports      lt_data_i_n[35]]; # P2 F12
set_property PACKAGE_PIN   D8 [get_ports      lt_data_i_n[36]]; # P1 C35
set_property PACKAGE_PIN  D10 [get_ports      lt_data_i_n[37]]; # P1 B36
set_property PACKAGE_PIN   F8 [get_ports      lt_data_i_n[38]]; # P1 C37
set_property PACKAGE_PIN AF15 [get_ports      lt_data_i_n[39]]; # P2 B15
set_property PACKAGE_PIN  Y26 [get_ports       lt_data_i_n[3]]; # P2 E5
set_property PACKAGE_PIN AF17 [get_ports      lt_data_i_n[40]]; # P2 C14
set_property PACKAGE_PIN AF20 [get_ports      lt_data_i_n[41]]; # P2 B17
set_property PACKAGE_PIN AC17 [get_ports      lt_data_i_n[42]]; # P2 F20
set_property PACKAGE_PIN AD19 [get_ports      lt_data_i_n[43]]; # P2 E21
set_property PACKAGE_PIN AB20 [get_ports      lt_data_i_n[44]]; # P2 F22
set_property PACKAGE_PIN AC22 [get_ports      lt_data_i_n[45]]; # P2 C10
set_property PACKAGE_PIN AF25 [get_ports      lt_data_i_n[46]]; # P2 B11
set_property PACKAGE_PIN AE26 [get_ports      lt_data_i_n[47]]; # P2 C12
set_property PACKAGE_PIN  B19 [get_ports      lt_data_i_n[48]]; # P1 E14
set_property PACKAGE_PIN  C18 [get_ports      lt_data_i_n[49]]; # P1 F13
set_property PACKAGE_PIN AB25 [get_ports       lt_data_i_n[4]]; # P2 F4
set_property PACKAGE_PIN  A19 [get_ports      lt_data_i_n[50]]; # P1 F15
set_property PACKAGE_PIN  F13 [get_ports      lt_data_i_n[51]]; # P1 E26
set_property PACKAGE_PIN  A15 [get_ports      lt_data_i_n[52]]; # P1 F25
set_property PACKAGE_PIN  E12 [get_ports      lt_data_i_n[53]]; # P1 E28
set_property PACKAGE_PIN AF18 [get_ports      lt_data_i_n[54]]; # P2 C16
set_property PACKAGE_PIN AD14 [get_ports      lt_data_i_n[55]]; # P2 B19
set_property PACKAGE_PIN AE16 [get_ports      lt_data_i_n[56]]; # P2 C18
set_property PACKAGE_PIN  W19 [get_ports      lt_data_i_n[57]]; # P2 E23
set_property PACKAGE_PIN  W16 [get_ports      lt_data_i_n[58]]; # P2 F24
set_property PACKAGE_PIN  W14 [get_ports      lt_data_i_n[59]]; # P2 E25
set_property PACKAGE_PIN AC24 [get_ports       lt_data_i_n[5]]; # P2 E7
set_property PACKAGE_PIN AF22 [get_ports      lt_data_i_n[60]]; # P2 B13
set_property PACKAGE_PIN  W21 [get_ports      lt_data_i_n[61]]; # P2 E3
set_property PACKAGE_PIN  V24 [get_ports      lt_data_i_n[62]]; # P2 F2
set_property PACKAGE_PIN  A14 [get_ports      lt_data_i_n[63]]; # P1 B26
set_property PACKAGE_PIN  C13 [get_ports      lt_data_i_n[64]]; # P1 C27
set_property PACKAGE_PIN  A12 [get_ports      lt_data_i_n[65]]; # P1 B28
set_property PACKAGE_PIN  F12 [get_ports      lt_data_i_n[66]]; # P1 F27
set_property PACKAGE_PIN  D11 [get_ports      lt_data_i_n[67]]; # P1 E30
set_property PACKAGE_PIN  F10 [get_ports      lt_data_i_n[68]]; # P1 F29
set_property PACKAGE_PIN AE20 [get_ports      lt_data_i_n[69]]; # P2 B21
set_property PACKAGE_PIN  D13 [get_ports       lt_data_i_n[6]]; # P1 C29
set_property PACKAGE_PIN  Y16 [get_ports      lt_data_i_n[70]]; # P2 C20
set_property PACKAGE_PIN  Y18 [get_ports      lt_data_i_n[71]]; # P2 B23
set_property PACKAGE_PIN AE15 [get_ports      lt_data_i_n[72]]; # P2 E15
set_property PACKAGE_PIN AC16 [get_ports      lt_data_i_n[73]]; # P2 F16
set_property PACKAGE_PIN AA18 [get_ports      lt_data_i_n[74]]; # P2 F14
set_property PACKAGE_PIN  B11 [get_ports       lt_data_i_n[7]]; # P1 B30
set_property PACKAGE_PIN  A10 [get_ports       lt_data_i_n[8]]; # P1 C31
set_property PACKAGE_PIN   H8 [get_ports       lt_data_i_n[9]]; # P1 E32
set_property PACKAGE_PIN  U24 [get_ports       lt_data_i_p[0]]; # P2 A1
set_property PACKAGE_PIN  G10 [get_ports      lt_data_i_p[10]]; # P1 E31
set_property PACKAGE_PIN  J13 [get_ports      lt_data_i_p[11]]; # P1 D34
set_property PACKAGE_PIN AA19 [get_ports      lt_data_i_p[12]]; # P2 B22
set_property PACKAGE_PIN  V18 [get_ports      lt_data_i_p[13]]; # P2 A25
set_property PACKAGE_PIN  V16 [get_ports      lt_data_i_p[14]]; # P2 B24
set_property PACKAGE_PIN  W25 [get_ports      lt_data_i_p[15]]; # P2 B4
set_property PACKAGE_PIN  W23 [get_ports      lt_data_i_p[16]]; # P2 A5
set_property PACKAGE_PIN AB26 [get_ports      lt_data_i_p[17]]; # P2 B6
set_property PACKAGE_PIN AA23 [get_ports      lt_data_i_p[18]]; # P2 E6
set_property PACKAGE_PIN AB21 [get_ports      lt_data_i_p[19]]; # P2 D9
set_property PACKAGE_PIN  U22 [get_ports       lt_data_i_p[1]]; # P2 B2
set_property PACKAGE_PIN  W20 [get_ports      lt_data_i_p[20]]; # P2 E8
set_property PACKAGE_PIN   A9 [get_ports      lt_data_i_p[21]]; # P1 A32
set_property PACKAGE_PIN   C9 [get_ports      lt_data_i_p[22]]; # P1 B33
set_property PACKAGE_PIN  C12 [get_ports      lt_data_i_p[23]]; # P1 A34
set_property PACKAGE_PIN  H14 [get_ports      lt_data_i_p[24]]; # P1 E33
set_property PACKAGE_PIN  J11 [get_ports      lt_data_i_p[25]]; # P1 D36
set_property PACKAGE_PIN  H12 [get_ports      lt_data_i_p[26]]; # P1 E35
set_property PACKAGE_PIN AA14 [get_ports      lt_data_i_p[27]]; # P2 D17
set_property PACKAGE_PIN AC18 [get_ports      lt_data_i_p[28]]; # P2 E18
set_property PACKAGE_PIN AB14 [get_ports      lt_data_i_p[29]]; # P2 D19
set_property PACKAGE_PIN  U26 [get_ports       lt_data_i_p[2]]; # P2 A3
set_property PACKAGE_PIN  Y23 [get_ports      lt_data_i_p[30]]; # P2 A7
set_property PACKAGE_PIN  Y22 [get_ports      lt_data_i_p[31]]; # P2 B8
set_property PACKAGE_PIN AD23 [get_ports      lt_data_i_p[32]]; # P2 A9
set_property PACKAGE_PIN AE23 [get_ports      lt_data_i_p[33]]; # P2 D11
set_property PACKAGE_PIN AD21 [get_ports      lt_data_i_p[34]]; # P2 E10
set_property PACKAGE_PIN AD25 [get_ports      lt_data_i_p[35]]; # P2 E12
set_property PACKAGE_PIN   D9 [get_ports      lt_data_i_p[36]]; # P1 B35
set_property PACKAGE_PIN  E10 [get_ports      lt_data_i_p[37]]; # P1 A36
set_property PACKAGE_PIN   F9 [get_ports      lt_data_i_p[38]]; # P1 B37
set_property PACKAGE_PIN AF14 [get_ports      lt_data_i_p[39]]; # P2 A15
set_property PACKAGE_PIN  Y25 [get_ports       lt_data_i_p[3]]; # P2 D5
set_property PACKAGE_PIN AE17 [get_ports      lt_data_i_p[40]]; # P2 B14
set_property PACKAGE_PIN AF19 [get_ports      lt_data_i_p[41]]; # P2 A17
set_property PACKAGE_PIN AB17 [get_ports      lt_data_i_p[42]]; # P2 E20
set_property PACKAGE_PIN AC19 [get_ports      lt_data_i_p[43]]; # P2 D21
set_property PACKAGE_PIN AB19 [get_ports      lt_data_i_p[44]]; # P2 E22
set_property PACKAGE_PIN AB22 [get_ports      lt_data_i_p[45]]; # P2 B10
set_property PACKAGE_PIN AF24 [get_ports      lt_data_i_p[46]]; # P2 A11
set_property PACKAGE_PIN AD26 [get_ports      lt_data_i_p[47]]; # P2 B12
set_property PACKAGE_PIN  C19 [get_ports      lt_data_i_p[48]]; # P1 D14
set_property PACKAGE_PIN  C17 [get_ports      lt_data_i_p[49]]; # P1 E13
set_property PACKAGE_PIN AA25 [get_ports       lt_data_i_p[4]]; # P2 E4
set_property PACKAGE_PIN  A18 [get_ports      lt_data_i_p[50]]; # P1 E15
set_property PACKAGE_PIN  F14 [get_ports      lt_data_i_p[51]]; # P1 D26
set_property PACKAGE_PIN  B15 [get_ports      lt_data_i_p[52]]; # P1 E25
set_property PACKAGE_PIN  E13 [get_ports      lt_data_i_p[53]]; # P1 D28
set_property PACKAGE_PIN AE18 [get_ports      lt_data_i_p[54]]; # P2 B16
set_property PACKAGE_PIN AC14 [get_ports      lt_data_i_p[55]]; # P2 A19
set_property PACKAGE_PIN AD16 [get_ports      lt_data_i_p[56]]; # P2 B18
set_property PACKAGE_PIN  W18 [get_ports      lt_data_i_p[57]]; # P2 D23
set_property PACKAGE_PIN  W15 [get_ports      lt_data_i_p[58]]; # P2 E24
set_property PACKAGE_PIN  V14 [get_ports      lt_data_i_p[59]]; # P2 D25
set_property PACKAGE_PIN AC23 [get_ports       lt_data_i_p[5]]; # P2 D7
set_property PACKAGE_PIN AE22 [get_ports      lt_data_i_p[60]]; # P2 A13
set_property PACKAGE_PIN  V21 [get_ports      lt_data_i_p[61]]; # P2 D3
set_property PACKAGE_PIN  V23 [get_ports      lt_data_i_p[62]]; # P2 E2
set_property PACKAGE_PIN  B14 [get_ports      lt_data_i_p[63]]; # P1 A26
set_property PACKAGE_PIN  C14 [get_ports      lt_data_i_p[64]]; # P1 B27
set_property PACKAGE_PIN  A13 [get_ports      lt_data_i_p[65]]; # P1 A28
set_property PACKAGE_PIN  G12 [get_ports      lt_data_i_p[66]]; # P1 E27
set_property PACKAGE_PIN  E11 [get_ports      lt_data_i_p[67]]; # P1 D30
set_property PACKAGE_PIN  G11 [get_ports      lt_data_i_p[68]]; # P1 E29
set_property PACKAGE_PIN AD20 [get_ports      lt_data_i_p[69]]; # P2 A21
set_property PACKAGE_PIN  D14 [get_ports       lt_data_i_p[6]]; # P1 B29
set_property PACKAGE_PIN  Y15 [get_ports      lt_data_i_p[70]]; # P2 B20
set_property PACKAGE_PIN  Y17 [get_ports      lt_data_i_p[71]]; # P2 A23
set_property PACKAGE_PIN AD15 [get_ports      lt_data_i_p[72]]; # P2 D15
set_property PACKAGE_PIN AB16 [get_ports      lt_data_i_p[73]]; # P2 E16
set_property PACKAGE_PIN AA17 [get_ports      lt_data_i_p[74]]; # P2 E14
set_property PACKAGE_PIN  B12 [get_ports       lt_data_i_p[7]]; # P1 A30
set_property PACKAGE_PIN  B10 [get_ports       lt_data_i_p[8]]; # P1 B31
set_property PACKAGE_PIN   H9 [get_ports       lt_data_i_p[9]]; # P1 D32
set_property PACKAGE_PIN AF10 [get_ports          lvs_sync[0]]; # P2 E34
set_property PACKAGE_PIN  AF8 [get_ports          lvs_sync[1]]; # P2 C34
set_property PACKAGE_PIN  AE8 [get_ports          lvs_sync[2]]; # P2 B34
set_property PACKAGE_PIN  AD8 [get_ports          lvs_sync[3]]; # P2 C28
set_property PACKAGE_PIN  AB9 [get_ports          lvs_sync[4]]; # P2 F28
set_property PACKAGE_PIN AA10 [get_ports         lvs_sync_ccb]; # P2 D29
set_property PACKAGE_PIN  K16 [get_ports         rb_data_o[0]]; # P1 A24
set_property PACKAGE_PIN  K20 [get_ports        rb_data_o[10]]; # P1 B23
set_property PACKAGE_PIN  H19 [get_ports        rb_data_o[11]]; # P1 A22
set_property PACKAGE_PIN  D16 [get_ports        rb_data_o[12]]; # P1 C17
set_property PACKAGE_PIN  M16 [get_ports        rb_data_o[13]]; # P1 B12
set_property PACKAGE_PIN  E21 [get_ports        rb_data_o[14]]; # P1 D10
set_property PACKAGE_PIN  E22 [get_ports        rb_data_o[15]]; # P1 E10
set_property PACKAGE_PIN  F23 [get_ports        rb_data_o[16]]; # P1 C7
set_property PACKAGE_PIN  F24 [get_ports        rb_data_o[17]]; # P1 B6
set_property PACKAGE_PIN  K23 [get_ports        rb_data_o[18]]; # P1 B3
set_property PACKAGE_PIN  H23 [get_ports        rb_data_o[19]]; # P1 E5
set_property PACKAGE_PIN  K17 [get_ports         rb_data_o[1]]; # P1 B24
set_property PACKAGE_PIN  G20 [get_ports        rb_data_o[20]]; # P1 B22
set_property PACKAGE_PIN  D19 [get_ports        rb_data_o[21]]; # P1 B21
set_property PACKAGE_PIN  A20 [get_ports        rb_data_o[22]]; # P1 E12
set_property PACKAGE_PIN  B21 [get_ports        rb_data_o[23]]; # P1 C11
set_property PACKAGE_PIN  D26 [get_ports        rb_data_o[24]]; # P1 A8
set_property PACKAGE_PIN  C26 [get_ports        rb_data_o[25]]; # P1 B8
set_property PACKAGE_PIN  G25 [get_ports        rb_data_o[26]]; # P1 E7
set_property PACKAGE_PIN  F25 [get_ports        rb_data_o[27]]; # P1 B5
set_property PACKAGE_PIN  L22 [get_ports        rb_data_o[28]]; # P1 D4
set_property PACKAGE_PIN  J23 [get_ports        rb_data_o[29]]; # P1 C3
set_property PACKAGE_PIN  F18 [get_ports         rb_data_o[2]]; # P1 C19
set_property PACKAGE_PIN  G17 [get_ports        rb_data_o[30]]; # P1 B19
set_property PACKAGE_PIN  K15 [get_ports        rb_data_o[31]]; # P1 A12
set_property PACKAGE_PIN  C22 [get_ports        rb_data_o[32]]; # P1 B10
set_property PACKAGE_PIN  A24 [get_ports        rb_data_o[33]]; # P1 F11
set_property PACKAGE_PIN  E25 [get_ports        rb_data_o[34]]; # P1 E9
set_property PACKAGE_PIN  H21 [get_ports        rb_data_o[35]]; # P1 D8
set_property PACKAGE_PIN  J26 [get_ports        rb_data_o[36]]; # P1 D6
set_property PACKAGE_PIN  J21 [get_ports        rb_data_o[37]]; # P1 A4
set_property PACKAGE_PIN  K22 [get_ports        rb_data_o[38]]; # P1 E4
set_property PACKAGE_PIN  J24 [get_ports        rb_data_o[39]]; # P1 E3
set_property PACKAGE_PIN  D15 [get_ports         rb_data_o[3]]; # P1 B17
set_property PACKAGE_PIN  C21 [get_ports        rb_data_o[40]]; # P1 B11
set_property PACKAGE_PIN  B20 [get_ports        rb_data_o[41]]; # P1 D12
set_property PACKAGE_PIN  D23 [get_ports        rb_data_o[42]]; # P1 B9
set_property PACKAGE_PIN  D24 [get_ports        rb_data_o[43]]; # P1 C9
set_property PACKAGE_PIN  G24 [get_ports        rb_data_o[44]]; # P1 A6
set_property PACKAGE_PIN  G21 [get_ports        rb_data_o[45]]; # P1 E8
set_property PACKAGE_PIN  G26 [get_ports        rb_data_o[46]]; # P1 F7
set_property PACKAGE_PIN  H22 [get_ports        rb_data_o[47]]; # P1 B4
set_property PACKAGE_PIN  H24 [get_ports        rb_data_o[48]]; # P1 F5
set_property PACKAGE_PIN  J25 [get_ports        rb_data_o[49]]; # P1 F3
set_property PACKAGE_PIN  D21 [get_ports         rb_data_o[4]]; # P1 A10
set_property PACKAGE_PIN  A23 [get_ports         rb_data_o[5]]; # P1 E11
set_property PACKAGE_PIN  G22 [get_ports         rb_data_o[6]]; # P1 B7
set_property PACKAGE_PIN  D25 [get_ports         rb_data_o[7]]; # P1 F9
set_property PACKAGE_PIN  E26 [get_ports         rb_data_o[8]]; # P1 C5
set_property PACKAGE_PIN  H26 [get_ports         rb_data_o[9]]; # P1 E6
set_property PACKAGE_PIN  L18 [get_ports         rgmii_clk125]; # P1 F23
set_property PACKAGE_PIN  M17 [get_ports          rgmii_int_n]; # P1 E23
set_property PACKAGE_PIN  L17 [get_ports            rgmii_mdc]; # P1 D24
set_property PACKAGE_PIN  J19 [get_ports           rgmii_mdio]; # P1 E22
set_property PACKAGE_PIN  K18 [get_ports        rgmii_reset_n]; # P1 E24
set_property PACKAGE_PIN  F17 [get_ports         rgmii_rx_clk]; # P1 D18
set_property PACKAGE_PIN  L19 [get_ports         rgmii_rx_ctl]; # P1 E21
set_property PACKAGE_PIN  F20 [get_ports         rgmii_rxd[0]]; # P1 E20
set_property PACKAGE_PIN  E20 [get_ports         rgmii_rxd[1]]; # P1 F19
set_property PACKAGE_PIN  E17 [get_ports         rgmii_rxd[2]]; # P1 E18
set_property PACKAGE_PIN  J20 [get_ports         rgmii_rxd[3]]; # P1 C23
set_property PACKAGE_PIN  J15 [get_ports         rgmii_tx_clk]; # P1 D16
set_property PACKAGE_PIN  J16 [get_ports         rgmii_tx_ctl]; # P1 E16
set_property PACKAGE_PIN  D20 [get_ports         rgmii_txd[0]]; # P1 C21
set_property PACKAGE_PIN  G19 [get_ports         rgmii_txd[1]]; # P1 D20
set_property PACKAGE_PIN  F19 [get_ports         rgmii_txd[2]]; # P1 E19
set_property PACKAGE_PIN  D18 [get_ports         rgmii_txd[3]]; # P1 F17
