set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

####################################################################################################################
#                                               CLOCK 100MHz                                                       #
####################################################################################################################
set_property -dict { PACKAGE_PIN "F22"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { CLK1 }]     ;               # IO_L12P_T1_MRCC_14            Sch = CLK1

####################################################################################################################
#                                               RESET & FAN PWM                                                    #
####################################################################################################################
set_property -dict { PACKAGE_PIN "K21"    IOSTANDARD LVCMOS33   SLEW FAST   } [get_ports { RESET }]    ;                # IO_0_14                       Sch = RSTPIN
set_property -dict { PACKAGE_PIN "N16"    IOSTANDARD LVCMOS33   SLEW FAST   PULLDOWN True} [get_ports { FAN_PWM }]  ;   # IO_0_13                       Sch = FAN_PWM

####################################################################################################################
#                                               FT601 Signals                                                      #
####################################################################################################################
set_property -dict { PACKAGE_PIN "N17"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[0] }]  ;               # IO_L20N_T3_13                 Sch = FT_D0
set_property -dict { PACKAGE_PIN "N18"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[1] }]  ;               # IO_L22P_T3_13                 Sch = FT_D1
set_property -dict { PACKAGE_PIN "M19"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[2] }]  ;               # IO_L22N_T3_13                 Sch = FT_D2
set_property -dict { PACKAGE_PIN "M20"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[3] }]  ;               # IO_L7N_T1_13                  Sch = FT_D3
set_property -dict { PACKAGE_PIN "N19"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[4] }]  ;               # IO_L7P_T1_13                  Sch = FT_D4
set_property -dict { PACKAGE_PIN "K25"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[5] }]  ;               # IO_L1P_T0_13                  Sch = FT_D5
set_property -dict { PACKAGE_PIN "K26"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[6] }]  ;               # IO_L1N_T0_13                  Sch = FT_D6
set_property -dict { PACKAGE_PIN "L24"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[7] }]  ;               # IO_L8N_T1_13                  Sch = FT_D7
set_property -dict { PACKAGE_PIN "L25"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[8] }]  ;               # IO_L3N_T0_DQS_13              Sch = FT_D8
set_property -dict { PACKAGE_PIN "M24"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[9] }]  ;               # IO_L8P_T1_13                  Sch = FT_D9
set_property -dict { PACKAGE_PIN "M25"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[10]}]  ;               # IO_L3P_T0_DQS_13              Sch = FT_D10
set_property -dict { PACKAGE_PIN "M26"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[11]}]  ;               # IO_L5N_T0_13                  Sch = FT_D11
set_property -dict { PACKAGE_PIN "N22"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[12]}]  ;               # IO_L12N_T1_MRCC_13            Sch = FT_D12
set_property -dict { PACKAGE_PIN "N24"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[13]}]  ;               # IO_L4N_T0_13                  Sch = FT_D13
set_property -dict { PACKAGE_PIN "N26"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[14]}]  ;               # IO_L5P_T0_13                  Sch = FT_D14
set_property -dict { PACKAGE_PIN "P16"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[15]}]  ;               # IO_L20P_T3_13                 Sch = FT_D15
set_property -dict { PACKAGE_PIN "R16"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[16]}]  ;               # IO_L21P_T3_DQS_13             Sch = FT_D16
set_property -dict { PACKAGE_PIN "V13"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[50]}];                          # IO_0_VRN_32                   Sch = B32_0_SE
set_property -dict { PACKAGE_PIN "W13"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[51]}];                          # IO_25_VRP_32                  Sch = B32_1_SE
set_property -dict { PACKAGE_PIN "AE17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[52]}];                          # IO_L1P_T0_32                  Sch = B32_0_P
set_property -dict { PACKAGE_PIN "AF17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[53]}];                          # IO_L1N_T0_32                  Sch = B32_0_N
set_property -dict { PACKAGE_PIN "AA17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[54]}];                          # IO_L11P_T1_SRCC_32            Sch = B32_10_P
set_property -dict { PACKAGE_PIN "AA18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[55]}];                          # IO_L11N_T1_SRCC_32            Sch = B32_10_N
set_property -dict { PACKAGE_PIN "AF14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[56]}];                          # IO_L2P_T0_32                  Sch = B32_1_P
set_property -dict { PACKAGE_PIN "AF15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[57]}];                          # IO_L2N_T0_32                  Sch = B32_1_N
set_property -dict { PACKAGE_PIN "AD15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[58]}];                          # IO_L4P_T0_32                  Sch = B32_3_P
set_property -dict { PACKAGE_PIN "AE15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[59]}];                          # IO_L4N_T0_32                  Sch = B32_3_N
set_property -dict { PACKAGE_PIN "AE18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[60]}];                          # IO_L3P_T0_DQS_32              Sch = B32_2_P
set_property -dict { PACKAGE_PIN "AF18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[61]}];                          # IO_L3N_T0_DQS_32              Sch = B32_2_N
set_property -dict { PACKAGE_PIN "AB16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[62]}];                          # IO_L12P_T1_MRCC_32            Sch = B32_11_P
set_property -dict { PACKAGE_PIN "AC16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[63]}];                          # IO_L12N_T1_MRCC_32            Sch = B32_11_N
set_property -dict { PACKAGE_PIN "AF19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[64]}];                          # IO_L5P_T0_32                  Sch = B32_4_P
set_property -dict { PACKAGE_PIN "AF20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[65]}];                          # IO_L5N_T0_32                  Sch = B32_4_N
set_property -dict { PACKAGE_PIN "AA14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[66]}];                          # IO_L7P_T1_32                  Sch = B32_6_P
set_property -dict { PACKAGE_PIN "AA15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[67]}];                          # IO_L7N_T1_32                  Sch = B32_6_N
set_property -dict { PACKAGE_PIN "AD16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[68]}];                          # IO_L6P_T0_32                  Sch = B32_5_P
set_property -dict { PACKAGE_PIN "AE16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[69]}];                          # IO_L6N_T0_VREF_32             Sch = B32_5_N
set_property -dict { PACKAGE_PIN "AC18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[70]}];                          # IO_L13P_T2_MRCC_32            Sch = B32_12_P
set_property -dict { PACKAGE_PIN "AD18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[71]}];                          # IO_L13N_T2_MRCC_32            Sch = B32_12_N
set_property -dict { PACKAGE_PIN "AC14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[72]}];                          # IO_L8P_T1_32                  Sch = B32_7_P
set_property -dict { PACKAGE_PIN "AD14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[73]}];                          # IO_L8N_T1_32                  Sch = B32_7_N
set_property -dict { PACKAGE_PIN "AB14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[74]}];                          # IO_L10P_T1_32                 Sch = B32_9_P
set_property -dict { PACKAGE_PIN "AB15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[75]}];                          # IO_L10N_T1_32                 Sch = B32_9_N
set_property -dict { PACKAGE_PIN "Y15"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[76]}];                          # IO_L9P_T1_DQS_32              Sch = B32_8_P
set_property -dict { PACKAGE_PIN "Y16"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[77]}];                          # IO_L9N_T1_DQS_32              Sch = B32_8_N
set_property -dict { PACKAGE_PIN "AB17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[78]}];                          # IO_L14P_T2_SRCC_32            Sch = B32_13_P
set_property -dict { PACKAGE_PIN "AC17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[79]}];                          # IO_L14N_T2_SRCC_32            Sch = B32_13_N
set_property -dict { PACKAGE_PIN "AD20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[80]}];                          # IO_L15P_T2_DQS_32             Sch = B32_14_P
set_property -dict { PACKAGE_PIN "AE20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[81]}];                          # IO_L15N_T2_DQS_32             Sch = B32_14_N
set_property -dict { PACKAGE_PIN "AC19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[82]}];                          # IO_L17P_T2_32                 Sch = B32_16_P
set_property -dict { PACKAGE_PIN "AD19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[83]}];                          # IO_L17N_T2_32                 Sch = B32_16_N
set_property -dict { PACKAGE_PIN "AA19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[84]}];                          # IO_L16P_T2_32                 Sch = B32_15_P
set_property -dict { PACKAGE_PIN "AA20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[85]}];                          # IO_L16N_T2_32                 Sch = B32_15_N
set_property -dict { PACKAGE_PIN "AB19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[86]}];                          # IO_L18P_T2_32                 Sch = B32_17_P
set_property -dict { PACKAGE_PIN "AB20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[87]}];                          # IO_L18N_T2_32                 Sch = B32_17_N
set_property -dict { PACKAGE_PIN "Y17"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[88]}];                          # IO_L19P_T3_32                 Sch = B32_18_P
set_property -dict { PACKAGE_PIN "Y18"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[89]}];                          # IO_L19N_T3_VREF_32            Sch = B32_18_N
set_property -dict { PACKAGE_PIN "W18"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[90]}];                          # IO_L21P_T3_DQS_32             Sch = B32_20_P
set_property -dict { PACKAGE_PIN "W19"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[91]}];                          # IO_L21N_T3_DQS_32             Sch = B32_20_N
set_property -dict { PACKAGE_PIN "V16"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[92]}];                          # IO_L20P_T3_32                 Sch = B32_19_P
set_property -dict { PACKAGE_PIN "V17"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[93]}];                          # IO_L20N_T3_32                 Sch = B32_19_N
set_property -dict { PACKAGE_PIN "W15"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[94]}];                          # IO_L22P_T3_32                 Sch = B32_21_P
set_property -dict { PACKAGE_PIN "W16"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[95]}];                          # IO_L22N_T3_32                 Sch = B32_21_N
set_property -dict { PACKAGE_PIN "V18"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[96]}];                          # IO_L23P_T3_32                 Sch = B32_22_P
set_property -dict { PACKAGE_PIN "V19"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[97]}];                          # IO_L23N_T3_32                 Sch = B32_22_N
set_property -dict { PACKAGE_PIN "V14"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[98]}];                          # IO_L24P_T3_32                 Sch = B32_23_P
set_property -dict { PACKAGE_PIN "W14"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[99]}];                          # IO_L24N_T3_32                 Sch = B32_23_N
set_property -dict { PACKAGE_PIN "U16"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[17]}]  ;               # IO_25_13                      Sch = FT_D17
set_property -dict { PACKAGE_PIN "R17"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[18]}]  ;               # IO_L21N_T3_DQS_13             Sch = FT_D18
set_property -dict { PACKAGE_PIN "T17"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[19]}]  ;               # IO_L23N_T3_13                 Sch = FT_D19
set_property -dict { PACKAGE_PIN "U17"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[20]}]  ;               # IO_L23P_T3_13                 Sch = FT_D20
set_property -dict { PACKAGE_PIN "R18"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[21]}]  ;               # IO_L24P_T3_13                 Sch = FT_D21
set_property -dict { PACKAGE_PIN "P26"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[22]}]  ;               # IO_L2N_T0_13                  Sch = FT_D22
set_property -dict { PACKAGE_PIN "P25"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[23]}]  ;               # IO_L6N_T0_VREF_13             Sch = FT_D23
set_property -dict { PACKAGE_PIN "P24"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[24]}]  ;               # IO_L4P_T0_13                  Sch = FT_D24
set_property -dict { PACKAGE_PIN "R26"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[25]}]  ;               # IO_L2P_T0_13                  Sch = FT_D25
set_property -dict { PACKAGE_PIN "R25"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[26]}]  ;               # IO_L6P_T0_13                  Sch = FT_D26
set_property -dict { PACKAGE_PIN "R23"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[27]}]  ;               # IO_L14N_T2_SRCC_13            Sch = FT_D27
set_property -dict { PACKAGE_PIN "T25"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[28]}]  ;               # IO_L15N_T2_DQS_13             Sch = FT_D28
set_property -dict { PACKAGE_PIN "T24"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[29]}]  ;               # IO_L15P_T2_DQS_13             Sch = FT_D29
set_property -dict { PACKAGE_PIN "R22"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[30]}]  ;               # IO_L14P_T2_SRCC_13            Sch = FT_D30
set_property -dict { PACKAGE_PIN "T22"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { DATA[31]}]  ;               # IO_L17P_T2_13                 Sch = FT_D31
set_property -dict { PACKAGE_PIN "P18"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { BE[0] }]    ;               # IO_L24N_T3_13                 Sch = FT_BE0
set_property -dict { PACKAGE_PIN "P19"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { BE[1] }]    ;               # IO_L9P_T1_DQS_13              Sch = FT_BE1
set_property -dict { PACKAGE_PIN "T18"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { BE[2] }]    ;               # IO_L19P_T3_13                 Sch = FT_BE2
set_property -dict { PACKAGE_PIN "T19"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { BE[3] }]    ;               # IO_L19N_T3_VREF_13            Sch = FT_BE3
set_property -dict { PACKAGE_PIN "U19"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { TXE_N }]    ;               # IO_L18P_T2_13                 Sch = FT_TXE
set_property -dict { PACKAGE_PIN "R20"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { RXF_N }]    ;               # IO_L16N_T2_13                 Sch = FT_RXE
set_property -dict { PACKAGE_PIN "R21"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { WR_N  }]    ;               # IO_L13P_T2_MRCC_13            Sch = FT_WR
set_property -dict { PACKAGE_PIN "P21"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { RD_N  }]    ;               # IO_L13N_T2_MRCC_13            Sch = FT_RD
set_property -dict { PACKAGE_PIN "N21"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { FT_CLK}]    ;               # IO_L12P_T1_MRCC_13            Sch = FT_CLK
set_property -dict { PACKAGE_PIN "T20"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { OE_N  }]    ;               # IO_L16P_T2_13                 Sch = FT_OE
set_property -dict { PACKAGE_PIN "T23"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { WAKEUP_N }] ;               # IO_L17N_T2_13                 Sch = FT_WK
set_property -dict { PACKAGE_PIN "U20"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { FT_RST}]    ;               # IO_L18N_T2_13                 Sch = FT_RST

####################################################################################################################
#                                        DDR3       : MT41J256M16XX-125                                            #
#                                        Frequency  : 400 MHz                                                      #
#                                        Data Width : 16                                                           #
####################################################################################################################
set_property -dict { PACKAGE_PIN "AD1"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[0]}]     ;               # IO_L20P_T3_34                 Sch = DDR3_DQ0
set_property -dict { PACKAGE_PIN "AE1"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[1]}]     ;               # IO_L20N_T3_34                 Sch = DDR3_DQ1
set_property -dict { PACKAGE_PIN "AE3"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[2]}]     ;               # IO_L22P_T3_34                 Sch = DDR3_DQ2
set_property -dict { PACKAGE_PIN "AE2"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[3]}]     ;               # IO_L22N_T3_34                 Sch = DDR3_DQ3
set_property -dict { PACKAGE_PIN "AE6"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[4]}]     ;               # IO_L23P_T3_34                 Sch = DDR3_DQ4
set_property -dict { PACKAGE_PIN "AE5"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[5]}]     ;               # IO_L23N_T3_34                 Sch = DDR3_DQ5
set_property -dict { PACKAGE_PIN "AF3"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[6]}]     ;               # IO_L24P_T3_34                 Sch = DDR3_DQ6
set_property -dict { PACKAGE_PIN "AF2"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[7]}]     ;               # IO_L24N_T3_34                 Sch = DDR3_DQ7
set_property -dict { PACKAGE_PIN "W11"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[8]}]     ;               # IO_L1N_T0_33                  Sch = DDR3_DQ8
set_property -dict { PACKAGE_PIN "V8"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[9]}]     ;               # IO_L2P_T0_33                  Sch = DDR3_DQ9
set_property -dict { PACKAGE_PIN "V7"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[10]}]    ;               # IO_L2N_T0_33                  Sch = DDR3_DQ10
set_property -dict { PACKAGE_PIN "Y8"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[11]}]    ;               # IO_L4P_T0_33                  Sch = DDR3_DQ11
set_property -dict { PACKAGE_PIN "Y7"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[12]}]    ;               # IO_L4N_T0_33                  Sch = DDR3_DQ12
set_property -dict { PACKAGE_PIN "Y11"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[13]}]    ;               # IO_L5P_T0_33                  Sch = DDR3_DQ13
set_property -dict { PACKAGE_PIN "Y10"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[14]}]    ;               # IO_L5N_T0_33                  Sch = DDR3_DQ14
set_property -dict { PACKAGE_PIN "V9"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dq[15]}]    ;               # IO_L6P_T0_33                  Sch = DDR3_DQ15
set_property -dict { PACKAGE_PIN "AC1"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[0]}]   ;               # IO_L9N_T1_DQS_34              Sch = DDR3_A0
set_property -dict { PACKAGE_PIN "AB1"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[1]}]   ;               # IO_L9P_T1_DQS_34              Sch = DDR3_A1
set_property -dict { PACKAGE_PIN "V1"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[2]}]   ;               # IO_L8N_T1_34                  Sch = DDR3_A2
set_property -dict { PACKAGE_PIN "V2"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[3]}]   ;               # IO_L8P_T1_34                  Sch = DDR3_A3
set_property -dict { PACKAGE_PIN "Y2"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[4]}]   ;               # IO_L7N_T1_34                  Sch = DDR3_A4
set_property -dict { PACKAGE_PIN "Y3"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[5]}]   ;               # IO_L7P_T1_34                  Sch = DDR3_A5
set_property -dict { PACKAGE_PIN "V4"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[6]}]   ;               # IO_L6P_T0_34                  Sch = DDR3_A6
set_property -dict { PACKAGE_PIN "V6"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[7]}]   ;               # IO_L5N_T0_34                  Sch = DDR3_A7
set_property -dict { PACKAGE_PIN "U7"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[8]}]   ;               # IO_L5P_T0_34                  Sch = DDR3_A8
set_property -dict { PACKAGE_PIN "W3"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[9]}]   ;               # IO_L4N_T0_34                  Sch = DDR3_A9
set_property -dict { PACKAGE_PIN "V3"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[10]}]  ;               # IO_L4P_T0_34                  Sch = DDR3_A10
set_property -dict { PACKAGE_PIN "U1"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[11]}]  ;               # IO_L2N_T0_34                  Sch = DDR3_A11
set_property -dict { PACKAGE_PIN "U2"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[12]}]  ;               # IO_L2P_T0_34                  Sch = DDR3_A12
set_property -dict { PACKAGE_PIN "U5"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[13]}]  ;               # IO_L1N_T0_34                  Sch = DDR3_A13
set_property -dict { PACKAGE_PIN "U6"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_addr[13]}]  ;               # IO_L1P_T0_34                  Sch = DDR3_A14
set_property -dict { PACKAGE_PIN "AB2"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_ba[0]}]     ;               # IO_L11P_T1_SRCC_34            Sch = DDR3_BA0
set_property -dict { PACKAGE_PIN "Y1"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_ba[1]}]     ;               # IO_L10N_T1_34                 Sch = DDR3_BA1
set_property -dict { PACKAGE_PIN "W1"     IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_ba[2]}]     ;               # IO_L10P_T1_34                 Sch = DDR3_BA2
set_property -dict { PACKAGE_PIN "AC2"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_ras_n}]     ;               # IO_L11N_T1_SRCC_34            Sch = DDR3_RASn
set_property -dict { PACKAGE_PIN "AA3"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_cas_n}]     ;               # IO_L12P_T1_MRCC_34            Sch = DDR3_CASn
set_property -dict { PACKAGE_PIN "AA2"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_we_n}]      ;               # IO_L12N_T1_MRCC_34            Sch = DDR3_WEn
set_property -dict { PACKAGE_PIN "AA4"    IOSTANDARD LVCMOS15   SLEW FAST} [get_ports {ddr3_reset_n}]   ;               # IO_L13P_T2_MRCC_34            Sch = DDR3_RESETn
set_property -dict { PACKAGE_PIN "AB5"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_cke}]       ;               # IO_L15N_T2_DQS_34             Sch = DDR3_CKE
set_property -dict { PACKAGE_PIN "AB6"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_odt}]       ;               # IO_L16P_T2_34                 Sch = DDR3_ODT
set_property -dict { PACKAGE_PIN "AA5"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_cs_n}]      ;               # IO_L15P_T2_DQS_34             Sch = DDR3_CSn
set_property -dict { PACKAGE_PIN "AD4"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dm[0]}]     ;               # IO_L19P_T3_34                 Sch = DDR3_DM0
set_property -dict { PACKAGE_PIN "V11"    IOSTANDARD SSTL15     SLEW FAST} [get_ports {ddr3_dm[1]}]     ;               # IO_L1P_T0_33                  Sch = DDR3_DM1
set_property -dict { PACKAGE_PIN "AF5"    IOSTANDARD DIFF_SSTL15 SLEW FAST} [get_ports {ddr3_dqs_p[0]}] ;               # IO_L21P_T3_DQS_34             Sch = DDR3_LDQS_P
set_property -dict { PACKAGE_PIN "AF4"    IOSTANDARD DIFF_SSTL15 SLEW FAST} [get_ports {ddr3_dqs_n[0]}] ;               # IO_L21N_T3_DQS_34             Sch = DDR3_LDQS_N
set_property -dict { PACKAGE_PIN "W10"    IOSTANDARD DIFF_SSTL15 SLEW FAST} [get_ports {ddr3_dqs_p[1]}] ;               # IO_L3P_T0_DQS_33              Sch = DDR3_UDQS_P
set_property -dict { PACKAGE_PIN "W9"     IOSTANDARD DIFF_SSTL15 SLEW FAST} [get_ports {ddr3_dqs_n[1]}] ;               # IO_L3N_T0_DQS_33              Sch = DDR3_UDQS_N
set_property -dict { PACKAGE_PIN "W6"     IOSTANDARD DIFF_SSTL15 SLEW FAST} [get_ports {ddr3_ck_p[0]}]  ;               # IO_L3P_T0_DQS_34              Sch = DDR3_CLK_P
set_property -dict { PACKAGE_PIN "W5"     IOSTANDARD DIFF_SSTL15 SLEW FAST} [get_ports {ddr3_ck_n[0]}]  ;               # IO_L3N_T0_DQS_34              Sch = DDR3_CLK_N

####################################################################################################################
#                                              QSPI - FLASH                                                        #
####################################################################################################################
set_property -dict { PACKAGE_PIN "C23"    IOSTANDARD LVCMOS33    SLEW FAST} [get_ports { SPI_CS_N }]     ;              # IO_L6P_T0_FCS_B_14            Sch = FLASH_CS_N
set_property -dict { PACKAGE_PIN "B24"    IOSTANDARD LVCMOS33    SLEW FAST} [get_ports { SPI_DQ[0] }]    ;              # IO_L1P_T0_D00_MOSI_14         Sch = FLASH_DQ0
set_property -dict { PACKAGE_PIN "A25"    IOSTANDARD LVCMOS33    SLEW FAST} [get_ports { SPI_DQ[1] }]    ;              # IO_L1N_T0_D01_DIN_14          Sch = FLASH_DQ1
set_property -dict { PACKAGE_PIN "B22"    IOSTANDARD LVCMOS33    SLEW FAST} [get_ports { SPI_DQ[2] }]    ;              # IO_L2P_T0_D02_14              Sch = FLASH_DQ2
set_property -dict { PACKAGE_PIN "A22"    IOSTANDARD LVCMOS33    SLEW FAST} [get_ports { SPI_DQ[3] }]    ;              # IO_L2N_T0_D03_14              Sch = FLASH_DQ3
set_property -dict { PACKAGE_PIN "C8"     IOSTANDARD LVCMOS33    SLEW FAST} [get_ports { SPI_SCK }]      ;              # CCLK_0                        Sch = FLASH_SCK

####################################################################################################################
#                                              TPM Interface                                                       #
####################################################################################################################
set_property -dict { PACKAGE_PIN "M22"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { TPM_MOSI }]     ;           # IO_L10N_T1_13                 Sch = TPM_MOSI
set_property -dict { PACKAGE_PIN "M21"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { TPM_MISO }]     ;           # IO_L10P_T1_13                 Sch = TPM_MISO
set_property -dict { PACKAGE_PIN "N23"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { TPM_CS#  }]     ;           # IO_L11N_T1_SRCC_13            Sch = TPM_CS#
set_property -dict { PACKAGE_PIN "P23"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { TPM_CLK  }]     ;           # IO_L11P_T1_SRCC_13            Sch = TPM_CLK
set_property -dict { PACKAGE_PIN "P20"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { TPM_RST# }]     ;           # IO_L9N_T1_DQS_13              Sch = TPM_RST#

###################################################################################################################
#                                                 Header P1                                                       #
###################################################################################################################
set_property -dict { PACKAGE_PIN "K23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[0]}];                           # IO_L24P_T3_A01_D17_14         Sch = B14_18_P
set_property -dict { PACKAGE_PIN "J23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[1]}];                           # IO_L24N_T3_A00_D16_14         Sch = B14_18_N
set_property -dict { PACKAGE_PIN "J24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[2]}];                           # IO_L22P_T3_A05_D21_14         Sch = B14_16_P
set_property -dict { PACKAGE_PIN "J25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[3]}];                           # IO_L22N_T3_A04_D20_14         Sch = B14_16_N
set_property -dict { PACKAGE_PIN "J21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[4]}];                           # IO_L21P_T3_DQS_14             Sch = B14_15_P
set_property -dict { PACKAGE_PIN "H22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[5]}];                           # IO_L21N_T3_DQS_A06_D22_14     Sch = B14_15_N
set_property -dict { PACKAGE_PIN "L22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[6]}];                           # IO_L23P_T3_A03_D19_14         Sch = B14_17_P
set_property -dict { PACKAGE_PIN "K22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[7]}];                           # IO_L23N_T3_A02_D18_14         Sch = B14_17_N
set_property -dict { PACKAGE_PIN "F25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[8]}];                           # IO_L17P_T2_A14_D30_14         Sch = B14_11_P
set_property -dict { PACKAGE_PIN "E26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[9]}];                           # IO_L17N_T2_A13_D29_14         Sch = B14_11_N
set_property -dict { PACKAGE_PIN "H23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[10]}];                          # IO_L20P_T3_A08_D24_14         Sch = B14_14_P
set_property -dict { PACKAGE_PIN "H24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[11]}];                          # IO_L20N_T3_A07_D23_14         Sch = B14_14_N
set_property -dict { PACKAGE_PIN "G24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[12]}];                          # IO_L14P_T2_SRCC_14            Sch = B14_8_P
set_property -dict { PACKAGE_PIN "F24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[13]}];                          # IO_L14N_T2_SRCC_14            Sch = B14_8_N
set_property -dict { PACKAGE_PIN "J26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[14]}];                          # IO_L18P_T2_A12_D28_14         Sch = B14_12_P
set_property -dict { PACKAGE_PIN "H26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[15]}];                          # IO_L18N_T2_A11_D27_14         Sch = B14_12_N
set_property -dict { PACKAGE_PIN "G22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[16]}];                          # IO_L13P_T2_MRCC_14            Sch = B14_7_P
set_property -dict { PACKAGE_PIN "F23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[17]}];                          # IO_L13N_T2_MRCC_14            Sch = B14_7_N
set_property -dict { PACKAGE_PIN "G25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[18]}];                          # IO_L16P_T2_CSI_B_14           Sch = B14_10_P
set_property -dict { PACKAGE_PIN "G26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[19]}];                          # IO_L16N_T2_A15_D31_14         Sch = B14_10_N
set_property -dict { PACKAGE_PIN "D26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[20]}];                          # IO_L5P_T0_D06_14              Sch = B14_1_P
set_property -dict { PACKAGE_PIN "C26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[21]}];                          # IO_L5N_T0_D07_14              Sch = B14_1_N
set_property -dict { PACKAGE_PIN "H21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[22]}];                          # IO_L19P_T3_A10_D26_14         Sch = B14_13_P
set_property -dict { PACKAGE_PIN "G21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[23]}];                          # IO_L19N_T3_A09_D25_VREF_14    Sch = B14_13_N
set_property -dict { PACKAGE_PIN "D23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[24]}];                          # IO_L11P_T1_SRCC_14            Sch = B14_6_P
set_property -dict { PACKAGE_PIN "D24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[25]}];                          # IO_L11N_T1_SRCC_14            Sch = B14_6_N
set_property -dict { PACKAGE_PIN "E25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[26]}];                          # IO_L15P_T2_DQS_RDWR_B_14      Sch = B14_9_P
set_property -dict { PACKAGE_PIN "D25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[27]}];                          # IO_L15N_T2_DQS_DOUT_CSO_B_14  Sch = B14_9_N
set_property -dict { PACKAGE_PIN "D21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[28]}];                          # IO_L7P_T1_D09_14              Sch = B14_2_P
set_property -dict { PACKAGE_PIN "C22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[29]}];                          # IO_L7N_T1_D10_14              Sch = B14_2_N
set_property -dict { PACKAGE_PIN "E21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[30]}];                          # IO_L9P_T1_DQS_14              Sch = B14_4_P
set_property -dict { PACKAGE_PIN "E22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[31]}];                          # IO_L9N_T1_DQS_D13_14          Sch = B14_4_N
set_property -dict { PACKAGE_PIN "C21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[32]}];                          # IO_L10P_T1_D14_14             Sch = B14_5_P
set_property -dict { PACKAGE_PIN "B21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[33]}];                          # IO_L10N_T1_D15_14             Sch = B14_5_N
set_property -dict { PACKAGE_PIN "A23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[34]}];                          # IO_L4P_T0_D04_14              Sch = B14_0_P
set_property -dict { PACKAGE_PIN "A24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[35]}];                          # IO_L4N_T0_D05_14              Sch = B14_0_N
set_property -dict { PACKAGE_PIN "K15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[36]}];                          # IO_0_15                       Sch = B15_0_SE
set_property -dict { PACKAGE_PIN "M16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[37]}];                          # IO_25_15                      Sch = B15_1_SE
set_property -dict { PACKAGE_PIN "B20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[38]}];                          # IO_L8P_T1_D11_14              Sch = B14_3_P
set_property -dict { PACKAGE_PIN "A20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[39]}];                          # IO_L8N_T1_D12_14              Sch = B14_3_N
set_property -dict { PACKAGE_PIN "C16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[40]}];                          # IO_L1P_T0_AD0P_15             Sch = B15_0_P
set_property -dict { PACKAGE_PIN "B16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[41]}];                          # IO_L1N_T0_AD0N_15             Sch = B15_0_N
set_property -dict { PACKAGE_PIN "C17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[42]}];                          # IO_L5P_T0_AD2P_15             Sch = B15_4_P
set_property -dict { PACKAGE_PIN "C18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[43]}];                          # IO_L5N_T0_AD2N_15             Sch = B15_4_N
set_property -dict { PACKAGE_PIN "B17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[44]}];                          # IO_L3P_T0_DQS_AD1P_15         Sch = B15_2_P
set_property -dict { PACKAGE_PIN "A17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[45]}];                          # IO_L3N_T0_DQS_AD1N_15         Sch = B15_2_N
set_property -dict { PACKAGE_PIN "C19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[46]}];                          # IO_L4P_T0_AD9P_15             Sch = B15_3_P
set_property -dict { PACKAGE_PIN "B19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[47]}];                          # IO_L4N_T0_AD9N_15             Sch = B15_3_N
set_property -dict { PACKAGE_PIN "H16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[48]}];                          # IO_L7P_T1_AD10P_15            Sch = B15_6_P
set_property -dict { PACKAGE_PIN "G16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[49]}];                          # IO_L7N_T1_AD10N_15            Sch = B15_6_N
set_property -dict { PACKAGE_PIN "A18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[50]}];                          # IO_L2P_T0_AD8P_15             Sch = B15_1_P
set_property -dict { PACKAGE_PIN "A19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[51]}];                          # IO_L2N_T0_AD8N_15             Sch = B15_1_N
set_property -dict { PACKAGE_PIN "G15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[52]}];                          # IO_L8P_T1_AD3P_15             Sch = B15_7_P
set_property -dict { PACKAGE_PIN "F15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[53]}];                          # IO_L8N_T1_AD3N_15             Sch = B15_7_N
set_property -dict { PACKAGE_PIN "J15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[54]}];                          # IO_L9P_T1_DQS_AD11P_15        Sch = B15_8_P
set_property -dict { PACKAGE_PIN "J16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[55]}];                          # IO_L9N_T1_DQS_AD11N_15        Sch = B15_8_N
set_property -dict { PACKAGE_PIN "D15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[56]}];                          # IO_L6P_T0_15                  Sch = B15_5_P
set_property -dict { PACKAGE_PIN "D16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[57]}];                          # IO_L6N_T0_VREF_15             Sch = B15_5_N
set_property -dict { PACKAGE_PIN "E18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[58]}];                          # IO_L13P_T2_MRCC_15            Sch = B15_12_P
set_property -dict { PACKAGE_PIN "D18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[59]}];                          # IO_L13N_T2_MRCC_15            Sch = B15_12_N
set_property -dict { PACKAGE_PIN "E15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[60]}];                          # IO_L10P_T1_AD4P_15            Sch = B15_9_P
set_property -dict { PACKAGE_PIN "E16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[61]}];                          # IO_L10N_T1_AD4N_15            Sch = B15_9_N
set_property -dict { PACKAGE_PIN "F17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[62]}];                          # IO_L12P_T1_MRCC_AD5P_15       Sch = B15_11_P
set_property -dict { PACKAGE_PIN "E17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[63]}];                          # IO_L12N_T1_MRCC_AD5N_15       Sch = B15_11_N
set_property -dict { PACKAGE_PIN "G17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[64]}];                          # IO_L11P_T1_SRCC_AD12P_15      Sch = B15_10_P
set_property -dict { PACKAGE_PIN "F18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[65]}];                          # IO_L11N_T1_SRCC_AD12N_15      Sch = B15_10_N
set_property -dict { PACKAGE_PIN "F19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[66]}];                          # IO_L17P_T2_A26_15             Sch = B15_16_P
set_property -dict { PACKAGE_PIN "E20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[67]}];                          # IO_L17N_T2_A25_15             Sch = B15_16_N
set_property -dict { PACKAGE_PIN "H17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[68]}];                          # IO_L14P_T2_SRCC_15            Sch = B15_13_P
set_property -dict { PACKAGE_PIN "H18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[69]}];                          # IO_L14N_T2_SRCC_15            Sch = B15_13_N
set_property -dict { PACKAGE_PIN "G19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[70]}];                          # IO_L16P_T2_A28_15             Sch = B15_15_P
set_property -dict { PACKAGE_PIN "F20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[71]}];                          # IO_L16N_T2_A27_15             Sch = B15_15_N
set_property -dict { PACKAGE_PIN "D19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[72]}];                          # IO_L15P_T2_DQS_15             Sch = B15_14_P
set_property -dict { PACKAGE_PIN "D20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[73]}];                          # IO_L15N_T2_DQS_ADV_B_15       Sch = B15_14_N
set_property -dict { PACKAGE_PIN "L19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[74]}];                          # IO_L21P_T3_DQS_15             Sch = B15_20_P
set_property -dict { PACKAGE_PIN "L20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[75]}];                          # IO_L21N_T3_DQS_A18_15         Sch = B15_20_N
set_property -dict { PACKAGE_PIN "H19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[76]}];                          # IO_L18P_T2_A24_15             Sch = B15_17_P
set_property -dict { PACKAGE_PIN "G20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[77]}];                          # IO_L18N_T2_A23_15             Sch = B15_17_N
set_property -dict { PACKAGE_PIN "J18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[78]}];                          # IO_L20P_T3_A20_15             Sch = B15_19_P
set_property -dict { PACKAGE_PIN "J19"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[79]}];                          # IO_L20N_T3_A19_15             Sch = B15_19_N
set_property -dict { PACKAGE_PIN "K20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[80]}];                          # IO_L19P_T3_A22_15             Sch = B15_18_P
set_property -dict { PACKAGE_PIN "J20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[81]}];                          # IO_L19N_T3_A21_VREF_15        Sch = B15_18_N
set_property -dict { PACKAGE_PIN "M17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[82]}];                          # IO_L23P_T3_FOE_B_15           Sch = B15_22_P
set_property -dict { PACKAGE_PIN "L18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[83]}];                          # IO_L23N_T3_FWE_B_15           Sch = B15_22_N
set_property -dict { PACKAGE_PIN "K16"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[84]}];                          # IO_L22P_T3_A17_15             Sch = B15_21_P
set_property -dict { PACKAGE_PIN "K17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[85]}];                          # IO_L22N_T3_A16_15             Sch = B15_21_N
set_property -dict { PACKAGE_PIN "L17"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[86]}];                          # IO_L24P_T3_RS1_15             Sch = B15_23_P
set_property -dict { PACKAGE_PIN "K18"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[87]}];                          # IO_L24N_T3_RS0_15             Sch = B15_23_N
set_property -dict { PACKAGE_PIN "J8"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[88]}];                          # IO_0_16                       Sch = B16_0_SE
set_property -dict { PACKAGE_PIN "J14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[89]}];                          # IO_25_16                      Sch = B16_1_SE
set_property -dict { PACKAGE_PIN "B15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[90]}];                          # IO_L23P_T3_16                 Sch = B16_22_P
set_property -dict { PACKAGE_PIN "A15"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[91]}];                          # IO_L23N_T3_16                 Sch = B16_22_N
set_property -dict { PACKAGE_PIN "B14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[92]}];                          # IO_L21P_T3_DQS_16             Sch = B16_20_P
set_property -dict { PACKAGE_PIN "A14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[93]}];                          # IO_L21N_T3_DQS_16             Sch = B16_20_N
set_property -dict { PACKAGE_PIN "F14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[94]}];                          # IO_L15P_T2_DQS_16             Sch = B16_14_P
set_property -dict { PACKAGE_PIN "F13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[95]}];                          # IO_L15N_T2_DQS_16             Sch = B16_14_N
set_property -dict { PACKAGE_PIN "C14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[96]}];                          # IO_L19P_T3_16                 Sch = B16_18_P
set_property -dict { PACKAGE_PIN "C13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[97]}];                          # IO_L19N_T3_VREF_16            Sch = B16_18_N
set_property -dict { PACKAGE_PIN "G12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[98]}];                          # IO_L16P_T2_16                 Sch = B16_15_P
set_property -dict { PACKAGE_PIN "F12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[99]}];                          # IO_L16N_T2_16                 Sch = B16_15_N
set_property -dict { PACKAGE_PIN "A13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[100]}];                         # IO_L24P_T3_16                 Sch = B16_23_P
set_property -dict { PACKAGE_PIN "A12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[101]}];                         # IO_L24N_T3_16                 Sch = B16_23_N
set_property -dict { PACKAGE_PIN "E13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[102]}];                         # IO_L18P_T2_16                 Sch = B16_17_P
set_property -dict { PACKAGE_PIN "E12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[103]}];                         # IO_L18N_T2_16                 Sch = B16_17_N
set_property -dict { PACKAGE_PIN "D14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[104]}];                         # IO_L17P_T2_16                 Sch = B16_16_P
set_property -dict { PACKAGE_PIN "D13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[105]}];                         # IO_L17N_T2_16                 Sch = B16_16_N
set_property -dict { PACKAGE_PIN "G11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[106]}];                         # IO_L11P_T1_SRCC_16            Sch = B16_10_P
set_property -dict { PACKAGE_PIN "F10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[107]}];                         # IO_L11N_T1_SRCC_16            Sch = B16_10_N
set_property -dict { PACKAGE_PIN "B12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[108]}];                         # IO_L20P_T3_16                 Sch = B16_19_P
set_property -dict { PACKAGE_PIN "B11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[109]}];                         # IO_L20N_T3_16                 Sch = B16_19_N
set_property -dict { PACKAGE_PIN "E11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[110]}];                         # IO_L14P_T2_SRCC_16            Sch = B16_13_P
set_property -dict { PACKAGE_PIN "D11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[111]}];                         # IO_L14N_T2_SRCC_16            Sch = B16_13_N
set_property -dict { PACKAGE_PIN "B10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[112]}];                         # IO_L22P_T3_16                 Sch = B16_21_P
set_property -dict { PACKAGE_PIN "A10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[113]}];                         # IO_L22N_T3_16                 Sch = B16_21_N
set_property -dict { PACKAGE_PIN "G10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[114]}];                         # IO_L2P_T0_16                  Sch = B16_1_P
set_property -dict { PACKAGE_PIN "G9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[115]}];                         # IO_L2N_T0_16                  Sch = B16_1_N
set_property -dict { PACKAGE_PIN "A9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[116]}];                         # IO_L9P_T1_DQS_16              Sch = B16_8_P
set_property -dict { PACKAGE_PIN "A8"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[117]}];                         # IO_L9N_T1_DQS_16              Sch = B16_8_N
set_property -dict { PACKAGE_PIN "H9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[118]}];                         # IO_L1P_T0_16                  Sch = B16_0_P
set_property -dict { PACKAGE_PIN "H8"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[119]}];                         # IO_L1N_T0_16                  Sch = B16_0_N
set_property -dict { PACKAGE_PIN "C9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[120]}];                         # IO_L10P_T1_16                 Sch = B16_9_P
set_property -dict { PACKAGE_PIN "B9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[121]}];                         # IO_L10N_T1_16                 Sch = B16_9_N
set_property -dict { PACKAGE_PIN "H14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[122]}];                         # IO_L5P_T0_16                  Sch = B16_4_P
set_property -dict { PACKAGE_PIN "G14"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[123]}];                         # IO_L5N_T0_16                  Sch = B16_4_N
set_property -dict { PACKAGE_PIN "C12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[124]}];                         # IO_L13P_T2_MRCC_16            Sch = B16_12_P
set_property -dict { PACKAGE_PIN "C11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[125]}];                         # IO_L13N_T2_MRCC_16            Sch = B16_12_N
set_property -dict { PACKAGE_PIN "J13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[126]}];                         # IO_L3P_T0_DQS_16              Sch = B16_2_P
set_property -dict { PACKAGE_PIN "H13"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[127]}];                         # IO_L3N_T0_DQS_16              Sch = B16_2_N
set_property -dict { PACKAGE_PIN "D9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[128]}];                         # IO_L8P_T1_16                  Sch = B16_7_P
set_property -dict { PACKAGE_PIN "D8"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[129]}];                         # IO_L8N_T1_16                  Sch = B16_7_N
set_property -dict { PACKAGE_PIN "H12"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[130]}];                         # IO_L6P_T0_16                  Sch = B16_5_P
set_property -dict { PACKAGE_PIN "H11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[131]}];                         # IO_L6N_T0_VREF_16             Sch = B16_5_N
set_property -dict { PACKAGE_PIN "E10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[132]}];                         # IO_L12P_T1_MRCC_16            Sch = B16_11_P
set_property -dict { PACKAGE_PIN "D10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[133]}];                         # IO_L12N_T1_MRCC_16            Sch = B16_11_N
set_property -dict { PACKAGE_PIN "J11"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[134]}];                         # IO_L4P_T0_16                  Sch = B16_3_P
set_property -dict { PACKAGE_PIN "J10"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[135]}];                         # IO_L4N_T0_16                  Sch = B16_3_N
set_property -dict { PACKAGE_PIN "F9"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[136]}];                         # IO_L7P_T1_16                  Sch = B16_6_P
set_property -dict { PACKAGE_PIN "F8"     IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P1[137]}];                         # IO_L7N_T1_16                  Sch = B16_6_N

###################################################################################################################
#                                               Header P2                                                         #
###################################################################################################################
set_property -dict { PACKAGE_PIN "U24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[0]}];                           # IO_L2P_T0_12                  Sch = B12_1_P
set_property -dict { PACKAGE_PIN "U25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[1]}];                           # IO_L2N_T0_12                  Sch = B12_1_N
set_property -dict { PACKAGE_PIN "U21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[2]}];                           # IO_0_12                       Sch = B12_0_SE
set_property -dict { PACKAGE_PIN "Y20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[3]}];                           # IO_25_12                      Sch = B12_1_SE
set_property -dict { PACKAGE_PIN "U22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[4]}];                           # IO_L1P_T0_12                  Sch = B12_0_P
set_property -dict { PACKAGE_PIN "V22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[5]}];                           # IO_L1N_T0_12                  Sch = B12_0_N
set_property -dict { PACKAGE_PIN "V23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[6]}];                           # IO_L3P_T0_DQS_12              Sch = B12_2_P
set_property -dict { PACKAGE_PIN "V24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[7]}];                           # IO_L3N_T0_DQS_12              Sch = B12_2_N
set_property -dict { PACKAGE_PIN "U26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[8]}];                           # IO_L4P_T0_12                  Sch = B12_3_P
set_property -dict { PACKAGE_PIN "V26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[9]}];                           # IO_L4N_T0_12                  Sch = B12_3_N
set_property -dict { PACKAGE_PIN "V21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[10]}];                          # IO_L6P_T0_12                  Sch = B12_5_P
set_property -dict { PACKAGE_PIN "W21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[11]}];                          # IO_L6N_T0_VREF_12             Sch = B12_5_N
set_property -dict { PACKAGE_PIN "W25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[12]}];                          # IO_L5P_T0_12                  Sch = B12_4_P
set_property -dict { PACKAGE_PIN "W26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[13]}];                          # IO_L5N_T0_12                  Sch = B12_4_N
set_property -dict { PACKAGE_PIN "AA25"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[14]}];                          # IO_L7P_T1_12                  Sch = B12_6_P
set_property -dict { PACKAGE_PIN "AB25"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[15]}];                          # IO_L7N_T1_12                  Sch = B12_6_N
set_property -dict { PACKAGE_PIN "W23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[16]}];                          # IO_L8P_T1_12                  Sch = B12_7_P
set_property -dict { PACKAGE_PIN "W24"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[17]}];                          # IO_L8N_T1_12                  Sch = B12_7_N
set_property -dict { PACKAGE_PIN "Y25"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[18]}];                          # IO_L10P_T1_12                 Sch = B12_9_P
set_property -dict { PACKAGE_PIN "Y26"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[19]}];                          # IO_L10N_T1_12                 Sch = B12_9_N
set_property -dict { PACKAGE_PIN "AB26"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[20]}];                          # IO_L9P_T1_DQS_12              Sch = B12_8_P
set_property -dict { PACKAGE_PIN "AC26"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[21]}];                          # IO_L9N_T1_DQS_12              Sch = B12_8_N
set_property -dict { PACKAGE_PIN "AA23"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[22]}];                          # IO_L11P_T1_SRCC_12            Sch = B12_10_P
set_property -dict { PACKAGE_PIN "AB24"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[23]}];                          # IO_L11N_T1_SRCC_12            Sch = B12_10_N
set_property -dict { PACKAGE_PIN "Y23"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[24]}];                          # IO_L12P_T1_MRCC_12            Sch = B12_11_P
set_property -dict { PACKAGE_PIN "AA24"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[25]}];                          # IO_L12N_T1_MRCC_12            Sch = B12_11_N
set_property -dict { PACKAGE_PIN "AC23"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[26]}];                          # IO_L14P_T2_SRCC_12            Sch = B12_13_P
set_property -dict { PACKAGE_PIN "AC24"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[27]}];                          # IO_L14N_T2_SRCC_12            Sch = B12_13_N
set_property -dict { PACKAGE_PIN "Y22"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[28]}];                          # IO_L13P_T2_MRCC_12            Sch = B12_12_P
set_property -dict { PACKAGE_PIN "AA22"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[29]}];                          # IO_L13N_T2_MRCC_12            Sch = B12_12_N
set_property -dict { PACKAGE_PIN "W20"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[30]}];                          # IO_L15P_T2_DQS_12             Sch = B12_14_P
set_property -dict { PACKAGE_PIN "Y21"    IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[31]}];                          # IO_L15N_T2_DQS_12             Sch = B12_14_N
set_property -dict { PACKAGE_PIN "AD23"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[32]}];                          # IO_L16P_T2_12                 Sch = B12_15_P
set_property -dict { PACKAGE_PIN "AD24"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[33]}];                          # IO_L16N_T2_12                 Sch = B12_15_N
set_property -dict { PACKAGE_PIN "AB21"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[34]}];                          # IO_L18P_T2_12                 Sch = B12_17_P
set_property -dict { PACKAGE_PIN "AC21"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[35]}];                          # IO_L18N_T2_12                 Sch = B12_17_N
set_property -dict { PACKAGE_PIN "AB22"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[36]}];                          # IO_L17P_T2_12                 Sch = B12_16_P
set_property -dict { PACKAGE_PIN "AC22"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[37]}];                          # IO_L17N_T2_12                 Sch = B12_16_N
set_property -dict { PACKAGE_PIN "AD21"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[38]}];                          # IO_L19P_T3_12                 Sch = B12_18_P
set_property -dict { PACKAGE_PIN "AE21"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[39]}];                          # IO_L19N_T3_VREF_12            Sch = B12_18_N
set_property -dict { PACKAGE_PIN "AF24"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[40]}];                          # IO_L20P_T3_12                 Sch = B12_19_P
set_property -dict { PACKAGE_PIN "AF25"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[41]}];                          # IO_L20N_T3_12                 Sch = B12_19_N
set_property -dict { PACKAGE_PIN "AE23"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[42]}];                          # IO_L22P_T3_12                 Sch = B12_21_P
set_property -dict { PACKAGE_PIN "AF23"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[43]}];                          # IO_L22N_T3_12                 Sch = B12_21_N
set_property -dict { PACKAGE_PIN "AD26"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[44]}];                          # IO_L21P_T3_DQS_12             Sch = B12_20_P
set_property -dict { PACKAGE_PIN "AE26"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[45]}];                          # IO_L21N_T3_DQS_12             Sch = B12_20_N
set_property -dict { PACKAGE_PIN "AD25"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[46]}];                          # IO_L23P_T3_12                 Sch = B12_22_P
set_property -dict { PACKAGE_PIN "AE25"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[47]}];                          # IO_L23N_T3_12                 Sch = B12_22_N
set_property -dict { PACKAGE_PIN "AE22"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[48]}];                          # IO_L24P_T3_12                 Sch = B12_23_P
set_property -dict { PACKAGE_PIN "AF22"   IOSTANDARD LVCMOS33 SLEW FAST} [get_ports {P2[49]}];                          # IO_L24N_T3_12                 Sch = B12_23_N
set_property -dict { PACKAGE_PIN "V13"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[50]}];                          # IO_0_VRN_32                   Sch = B32_0_SE
set_property -dict { PACKAGE_PIN "W13"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[51]}];                          # IO_25_VRP_32                  Sch = B32_1_SE
set_property -dict { PACKAGE_PIN "AE17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[52]}];                          # IO_L1P_T0_32                  Sch = B32_0_P
set_property -dict { PACKAGE_PIN "AF17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[53]}];                          # IO_L1N_T0_32                  Sch = B32_0_N
set_property -dict { PACKAGE_PIN "AA17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[54]}];                          # IO_L11P_T1_SRCC_32            Sch = B32_10_P
set_property -dict { PACKAGE_PIN "AA18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[55]}];                          # IO_L11N_T1_SRCC_32            Sch = B32_10_N
set_property -dict { PACKAGE_PIN "AF14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[56]}];                          # IO_L2P_T0_32                  Sch = B32_1_P
set_property -dict { PACKAGE_PIN "AF15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[57]}];                          # IO_L2N_T0_32                  Sch = B32_1_N
set_property -dict { PACKAGE_PIN "AD15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[58]}];                          # IO_L4P_T0_32                  Sch = B32_3_P
set_property -dict { PACKAGE_PIN "AE15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[59]}];                          # IO_L4N_T0_32                  Sch = B32_3_N
set_property -dict { PACKAGE_PIN "AE18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[60]}];                          # IO_L3P_T0_DQS_32              Sch = B32_2_P
set_property -dict { PACKAGE_PIN "AF18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[61]}];                          # IO_L3N_T0_DQS_32              Sch = B32_2_N
set_property -dict { PACKAGE_PIN "AB16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[62]}];                          # IO_L12P_T1_MRCC_32            Sch = B32_11_P
set_property -dict { PACKAGE_PIN "AC16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[63]}];                          # IO_L12N_T1_MRCC_32            Sch = B32_11_N
set_property -dict { PACKAGE_PIN "AF19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[64]}];                          # IO_L5P_T0_32                  Sch = B32_4_P
set_property -dict { PACKAGE_PIN "AF20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[65]}];                          # IO_L5N_T0_32                  Sch = B32_4_N
set_property -dict { PACKAGE_PIN "AA14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[66]}];                          # IO_L7P_T1_32                  Sch = B32_6_P
set_property -dict { PACKAGE_PIN "AA15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[67]}];                          # IO_L7N_T1_32                  Sch = B32_6_N
set_property -dict { PACKAGE_PIN "AD16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[68]}];                          # IO_L6P_T0_32                  Sch = B32_5_P
set_property -dict { PACKAGE_PIN "AE16"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[69]}];                          # IO_L6N_T0_VREF_32             Sch = B32_5_N
set_property -dict { PACKAGE_PIN "AC18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[70]}];                          # IO_L13P_T2_MRCC_32            Sch = B32_12_P
set_property -dict { PACKAGE_PIN "AD18"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[71]}];                          # IO_L13N_T2_MRCC_32            Sch = B32_12_N
set_property -dict { PACKAGE_PIN "AC14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[72]}];                          # IO_L8P_T1_32                  Sch = B32_7_P
set_property -dict { PACKAGE_PIN "AD14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[73]}];                          # IO_L8N_T1_32                  Sch = B32_7_N
set_property -dict { PACKAGE_PIN "AB14"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[74]}];                          # IO_L10P_T1_32                 Sch = B32_9_P
set_property -dict { PACKAGE_PIN "AB15"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[75]}];                          # IO_L10N_T1_32                 Sch = B32_9_N
set_property -dict { PACKAGE_PIN "Y15"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[76]}];                          # IO_L9P_T1_DQS_32              Sch = B32_8_P
set_property -dict { PACKAGE_PIN "Y16"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[77]}];                          # IO_L9N_T1_DQS_32              Sch = B32_8_N
set_property -dict { PACKAGE_PIN "AB17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[78]}];                          # IO_L14P_T2_SRCC_32            Sch = B32_13_P
set_property -dict { PACKAGE_PIN "AC17"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[79]}];                          # IO_L14N_T2_SRCC_32            Sch = B32_13_N
set_property -dict { PACKAGE_PIN "AD20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[80]}];                          # IO_L15P_T2_DQS_32             Sch = B32_14_P
set_property -dict { PACKAGE_PIN "AE20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[81]}];                          # IO_L15N_T2_DQS_32             Sch = B32_14_N
set_property -dict { PACKAGE_PIN "AC19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[82]}];                          # IO_L17P_T2_32                 Sch = B32_16_P
set_property -dict { PACKAGE_PIN "AD19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[83]}];                          # IO_L17N_T2_32                 Sch = B32_16_N
set_property -dict { PACKAGE_PIN "AA19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[84]}];                          # IO_L16P_T2_32                 Sch = B32_15_P
set_property -dict { PACKAGE_PIN "AA20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[85]}];                          # IO_L16N_T2_32                 Sch = B32_15_N
set_property -dict { PACKAGE_PIN "AB19"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[86]}];                          # IO_L18P_T2_32                 Sch = B32_17_P
set_property -dict { PACKAGE_PIN "AB20"   IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[87]}];                          # IO_L18N_T2_32                 Sch = B32_17_N
set_property -dict { PACKAGE_PIN "Y17"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[88]}];                          # IO_L19P_T3_32                 Sch = B32_18_P
set_property -dict { PACKAGE_PIN "Y18"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[89]}];                          # IO_L19N_T3_VREF_32            Sch = B32_18_N
set_property -dict { PACKAGE_PIN "W18"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[90]}];                          # IO_L21P_T3_DQS_32             Sch = B32_20_P
set_property -dict { PACKAGE_PIN "W19"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[91]}];                          # IO_L21N_T3_DQS_32             Sch = B32_20_N
set_property -dict { PACKAGE_PIN "V16"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[92]}];                          # IO_L20P_T3_32                 Sch = B32_19_P
set_property -dict { PACKAGE_PIN "V17"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[93]}];                          # IO_L20N_T3_32                 Sch = B32_19_N
set_property -dict { PACKAGE_PIN "W15"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[94]}];                          # IO_L22P_T3_32                 Sch = B32_21_P
set_property -dict { PACKAGE_PIN "W16"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[95]}];                          # IO_L22N_T3_32                 Sch = B32_21_N
set_property -dict { PACKAGE_PIN "V18"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[96]}];                          # IO_L23P_T3_32                 Sch = B32_22_P
set_property -dict { PACKAGE_PIN "V19"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[97]}];                          # IO_L23N_T3_32                 Sch = B32_22_N
set_property -dict { PACKAGE_PIN "V14"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[98]}];                          # IO_L24P_T3_32                 Sch = B32_23_P
set_property -dict { PACKAGE_PIN "W14"    IOSTANDARD LVCMOS18 SLEW FAST} [get_ports {P2[99]}];                          # IO_L24N_T3_32                 Sch = B32_23_N
set_property -dict { PACKAGE_PIN "AE7"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[100]}];                         # IO_L7P_T1_33                  Sch = B33_0_P
set_property -dict { PACKAGE_PIN "AF7"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[101]}];                         # IO_L7N_T1_33                  Sch = B33_0_N
set_property -dict { PACKAGE_PIN "U9"     IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[102]}];                         # IO_0_VRN_33                   Sch = B33_0_SE
set_property -dict { PACKAGE_PIN "V12"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[103]}];                         # IO_25_VRP_33                  Sch = B33_1_SE
set_property -dict { PACKAGE_PIN "AA8"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[104]}];                         # IO_L8P_T1_33                  Sch = B33_1_P
set_property -dict { PACKAGE_PIN "AA7"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[105]}];                         # IO_L8N_T1_33                  Sch = B33_1_N
set_property -dict { PACKAGE_PIN "AB7"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[106]}];                         # IO_L10P_T1_33                 Sch = B33_3_P
set_property -dict { PACKAGE_PIN "AC7"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[107]}];                         # IO_L10N_T1_33                 Sch = B33_3_N
set_property -dict { PACKAGE_PIN "AC8"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[108]}];                         # IO_L9P_T1_DQS_33              Sch = B33_2_P
set_property -dict { PACKAGE_PIN "AD8"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[109]}];                         # IO_L9N_T1_DQS_33              Sch = B33_2_N
set_property -dict { PACKAGE_PIN "AA9"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[110]}];                         # IO_L11P_T1_SRCC_33            Sch = B33_4_P
set_property -dict { PACKAGE_PIN "AB9"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[111]}];                         # IO_L11N_T1_SRCC_33            Sch = B33_4_N
set_property -dict { PACKAGE_PIN "AC9"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[112]}];                         # IO_L12P_T1_MRCC_33            Sch = B33_5_P
set_property -dict { PACKAGE_PIN "AD9"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[113]}];                         # IO_L12N_T1_MRCC_33            Sch = B33_5_N
set_property -dict { PACKAGE_PIN "AA10"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[114]}];                         # IO_L14P_T2_SRCC_33            Sch = B33_7_P
set_property -dict { PACKAGE_PIN "AB10"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[115]}];                         # IO_L14N_T2_SRCC_33            Sch = B33_7_N
set_property -dict { PACKAGE_PIN "AB11"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[116]}];                         # IO_L13P_T2_MRCC_33            Sch = B33_6_P
set_property -dict { PACKAGE_PIN "AC11"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[117]}];                         # IO_L13N_T2_MRCC_33            Sch = B33_6_N
set_property -dict { PACKAGE_PIN "AB12"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[118]}];                         # IO_L15P_T2_DQS_33             Sch = B33_8_P
set_property -dict { PACKAGE_PIN "AC12"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[119]}];                         # IO_L15N_T2_DQS_33             Sch = B33_8_N
set_property -dict { PACKAGE_PIN "AA13"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[120]}];                         # IO_L16P_T2_33                 Sch = B33_9_P
set_property -dict { PACKAGE_PIN "AA12"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[121]}];                         # IO_L16N_T2_33                 Sch = B33_9_N
set_property -dict { PACKAGE_PIN "Y13"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[122]}];                         # IO_L18P_T2_33                 Sch = B33_11_P
set_property -dict { PACKAGE_PIN "Y12"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[123]}];                         # IO_L18N_T2_33                 Sch = B33_11_N
set_property -dict { PACKAGE_PIN "AC13"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[124]}];                         # IO_L17P_T2_33                 Sch = B33_10_P
set_property -dict { PACKAGE_PIN "AD13"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[125]}];                         # IO_L17N_T2_33                 Sch = B33_10_N
set_property -dict { PACKAGE_PIN "AD10"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[126]}];                         # IO_L20P_T3_33                 Sch = B33_12_P
set_property -dict { PACKAGE_PIN "AE10"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[127]}];                         # IO_L20N_T3_33                 Sch = B33_12_N
set_property -dict { PACKAGE_PIN "AE12"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[128]}];                         # IO_L21P_T3_DQS_33             Sch = B33_13_P
set_property -dict { PACKAGE_PIN "AF12"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[129]}];                         # IO_L21N_T3_DQS_33             Sch = B33_13_N
set_property -dict { PACKAGE_PIN "AE13"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[130]}];                         # IO_L23P_T3_33                 Sch = B33_15_P
set_property -dict { PACKAGE_PIN "AF13"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[131]}];                         # IO_L23N_T3_33                 Sch = B33_15_N
set_property -dict { PACKAGE_PIN "AE8"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[132]}];                         # IO_L22P_T3_33                 Sch = B33_14_P
set_property -dict { PACKAGE_PIN "AF8"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[133]}];                         # IO_L22N_T3_33                 Sch = B33_14_N
set_property -dict { PACKAGE_PIN "AF10"   IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[134]}];                         # IO_L24P_T3_33                 Sch = B33_16_P
set_property -dict { PACKAGE_PIN "AF9"    IOSTANDARD LVCMOS15 SLEW FAST} [get_ports {P2[135]}];                         # IO_L24N_T3_33                 Sch = B33_16_N
